name: Go
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Checkout
        uses: actions/checkout@v2

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.45.2
          args: --issues-exit-code=0 # Temporarily make this warning instead of error

      - name: Static Check
        uses: dominikh/staticcheck-action@v1.1.0
        with:
          version: "2022.1"
          install-go: false
        continue-on-error: true

      - name: Build
        run: go build -v ./...
#
#      - name: Test
#        run: go test -v -count=1 ./...


      - name: Fetch Gox
        run: go get github.com/mitchellh/gox

  releases:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # build and publish in parallel: linux/386, linux/amd64, linux/arm64, windows/386, windows/amd64, darwin/amd64, darwin/arm64
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        exclude:
          - goarch: arm64
            goos: windows
    steps:
    - uses: actions/checkout@v2
    - uses: wangyoucao577/go-release-action@v1.25
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        goversion: "https://dl.google.com/go/go1.18.linux-amd64.tar.gz"
        project_path: "./src/swamp/"
        binary_name: "swamp"
