name: Go
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.6

      - name: Checkout
        uses: actions/checkout@v2

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.36
          args: --issues-exit-code=0 # Temporarily make this warning instead of error

      - name: Static Check
        uses: dominikh/staticcheck-action@v1.1.0
        with:
          version: "2021.1.2"
        continue-on-error: true

      - name: Build
        run: go build -v ./...
#
#      - name: Test
#        run: go test -v -count=1 ./...


      - name: Fetch Gox
        run: go get github.com/mitchellh/gox

      - name: Compile for all platforms
        run: $HOME/go/bin/gox -os="linux darwin windows" -arch="amd64" -output="build/{{.Dir}}_{{.OS}}_{{.Arch}}" -ldflags "-X main.Version=${{steps.get_version.version}}" -verbose ./...

      - name: Tar together executables
        run: tar -cvf build.tar build/

      - name: Upload executables
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: build.tar
