name: Go
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.6

      - name: Checkout
        uses: actions/checkout@v2

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.36
          args: --issues-exit-code=0 # Temporarily make this warning instead of error

      - name: Build
        run: go build -v ./...
#
#      - name: Test
#        run: go test -v -count=1 ./...


      - name: Fetch Gox
        run: go get github.com/mitchellh/gox

      - name: Compile for all platforms
        run: $HOME/go/bin/gox -os="linux darwin windows" -arch="amd64" -ldflags "-X main.Version=0.0.0" -verbose ./...

      - name: Upload executables
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: |
            swamp_darwin_amd64
            swamp_linux_amd64
            swamp_windows_amd64.exe