name: Go
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Checkout
        uses: actions/checkout@v2

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.45.2
          args: --issues-exit-code=0 # Temporarily make this warning instead of error

      - name: Static Check
        uses: dominikh/staticcheck-action@v1.1.0
        with:
          version: "2022.1"
          install-go: false
        continue-on-error: true

  #
  #      - name: Test
  #        run: go test -v -count=1 ./...

  releases:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # build and publish in parallel: linux/386, linux/amd64, linux/arm64, windows/386, windows/amd64, darwin/amd64, darwin/arm64
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        exclude:
          - goarch: arm64
            goos: windows
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Checkout
        uses: actions/checkout@v2

      - name: Compile for ${{ matrix.goos }} and ${{ matrix.goarch }}
        run: GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -v -o swamp_${{ matrix.goos }}_${{ matrix.goarch }} ./src/swamp/

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Executable
          path: swamp_${{ matrix.goos }}_${{ matrix.goarch }}
